# Práctica / Proyecto — Sistema de recomendación con embeddings modernos

## Contexto

A lo largo de la asignatura hemos trabajado con enfoques clásicos de sistemas de recomendación:
- recomendadores simples,
- recomendadores basados en contenido,
- filtrado colaborativo,
- e híbridos.

En esta práctica se propone dar un paso más y explorar si **los embeddings obtenidos con IA moderna** pueden ofrecer una representación más rica de los ítems y, en consecuencia, recomendaciones de mayor calidad.

La idea central del proyecto es que diseñéis, implementéis y evaluéis un **recomendador basado en embeddings** y lo comparéis con **uno o varios enfoques tradicionales**.

---

## Idea general

No se trata solo de “usar embeddings porque sí”.

Queremos que penséis como un equipo de Data Science que debe responder, con evidencias, a preguntas como:

- ¿Qué información del dataset merece la pena usar?
- ¿Cómo conviene convertir esa información a texto antes de obtener embeddings?
- ¿Mejora realmente el sistema frente a enfoques más sencillos?
- ¿En qué escenarios mejora, en cuáles no, y por qué?
- ¿Qué métricas y protocolo experimental son razonables para defender esa conclusión?

---

## Libertad de implementación

Podéis elegir la tecnología que queráis para obtener embeddings, por ejemplo:
- APIs externas,
- modelos open-source en local,
- herramientas tipo servidor local de modelos,
- u otras alternativas equivalentes.

También podéis usar embeddings generados por un modelo generalista o por un modelo específico de retrieval / embeddings.

Lo importante no es la marca de la herramienta, sino:
1. que expliquéis bien vuestra decisión,
2. que el pipeline sea reproducible,
3. y que la comparación experimental esté bien planteada.

# Objetivos de aprendizaje

Al finalizar esta práctica deberíais ser capaces de:

1. Diseñar un problema de recomendación a partir de un dataset real.
2. Construir una representación útil de los ítems a partir de texto, metadatos o ambas cosas.
3. Implementar un recomendador moderno basado en embeddings.
4. Compararlo con métodos tradicionales de recomendación.
5. Diseñar una evaluación razonable.
6. Analizar críticamente resultados, limitaciones, retos y posibles mejoras.

# Enunciado

## Tarea principal

Desarrollad un **sistema de recomendación basado en embeddings modernos** y comparadlo con **uno o varios sistemas tradicionales** sobre un dataset elegido por vuestro equipo.

El trabajo debe incluir, como mínimo:

### 1. Elección del dataset
Seleccionad un dataset adecuado para recomendación. El dominio es libre:
- películas,
- libros,
- videojuegos,
- música,
- productos,
- noticias,
- cursos,
- recetas,
- alojamientos,
- etc.

El dataset elegido debe permitir al menos una de estas dos posibilidades:
- construir recomendaciones a partir de **contenido / metadatos / texto**, o
- combinar contenido con algún tipo de **interacción usuario-ítem** si disponéis de ella.

### 2. Diseño de la representación del ítem
Debéis decidir **qué información incluir** para representar cada ítem.

Por ejemplo, según el dataset, podríais usar:
- título,
- descripción,
- categorías,
- tags,
- autor / director / marca,
- actores,
- keywords,
- atributos técnicos,
- precio,
- reseñas,
- combinaciones de varias columnas,
- etc.

No basta con concatenar columnas sin pensar.

Debéis justificar:
- qué columnas habéis escogido,
- cuáles habéis descartado,
- cómo las habéis limpiado,
- y cómo las habéis convertido en un único string o estructura textual antes de obtener embeddings.

### 3. Recomendador basado en embeddings
Implementad un sistema que use embeddings para recomendar ítems.

Algunas posibilidades:
- similitud ítem–ítem,
- perfil de usuario construido a partir de ítems consumidos,
- consulta textual + retrieval semántico,
- enfoque híbrido entre contenido y señales de interacción.

### 4. Comparación con métodos más tradicionales
Debéis implementar y comparar vuestro enfoque con **uno o varios baseline** más sencillos.

Ejemplos de baseline razonables (los vistos en clase):
- recomendador simple por popularidad o score,
- TF-IDF + similitud coseno,
- CountVectorizer / bag-of-words,
- metadata soup clásica,
- filtrado colaborativo user-based o item-based,
- kNN,
- SVD / matrix factorization,
- híbrido simple.

### 5. Evaluación
Debéis investigar y justificar **cómo evaluar** el sistema.

No hay una única respuesta correcta: la evaluación depende del tipo de recomendación que planteéis.

Por tanto, tendréis que decidir:
- qué partición de datos es razonable,
- qué escenario de test estáis simulando,
- qué métricas son adecuadas,
- y cómo interpretar si hay mejora real o no.

### 6. Discusión crítica
Además de mostrar resultados, debéis reflexionar sobre:
- retos encontrados,
- limitaciones del enfoque,
- coste computacional,
- dependencia del texto / metadatos,
- cold start,
- calidad de embeddings,
- sensibilidad a cómo construís el string,
- escenarios donde el método moderno ayuda,
- y escenarios donde un baseline clásico puede seguir siendo mejor.

# Restricciones mínimas del proyecto

## Mínimos obligatorios

El trabajo **debe** contener como mínimo lo siguiente:

- Un dataset real elegido por el equipo.
- Un análisis exploratorio breve pero útil del dataset.
- Un pipeline de preparación de datos reproducible.
- Un sistema de recomendación basado en embeddings modernos.
- Al menos **un baseline tradicional** bien implementado.
- Una comparación cuantitativa y una comparación cualitativa.
- Una sección final de conclusiones.

## Recomendación fuerte

Aunque el mínimo es **1 baseline**, es muy recomendable incluir **2 baselines**:
- uno muy sencillo,
- y otro más competitivo.

Ejemplo:
- baseline 1: popularidad / score,
- baseline 2: TF-IDF o filtrado colaborativo,
- modelo final: embeddings modernos.

# Sugerencias para elegir el dataset

## Qué buscamos en un buen dataset para esta práctica

Idealmente, vuestro dataset debería tener:
- suficientes ítems para que recomendar tenga sentido,
- metadatos o texto útiles,
- cierta variedad semántica,
- y, si es posible, alguna señal de interacción o preferencia.

## Ejemplos de datasets adecuados

Podéis buscar datasets en:
- Kaggle,
- Hugging Face Datasets,
- MovieLens,
- Amazon Reviews,
- Goodbooks,
- datasets de Spotify,
- Steam,
- Last.fm,
- artículos / noticias,
- catálogos de productos,
- u otras fuentes abiertas.

## Consejo importante

No elijáis un dataset gigantesco si luego no podéis procesarlo ni evaluarlo bien.

En esta práctica suele valer más:
- un dataset **moderado**,
- bien entendido,
- bien limpiado,
- y bien evaluado,

que un dataset enorme con un pipeline incompleto o poco defendible.

In [1]:
# Espacio de trabajo: elección y carga del dataset

# - indicar la fuente del dataset: https://www.kaggle.com/datasets/timstafford/pitchfork-reviews
# - cargar los datos y mostrar su estructura básica
import pandas as pd
music = pd.read_excel('pitchfork_reviews.xlsx')
display(music)
# - dejar claro qué representa un ítem y, si aplica, qué representa un usuario
# the albums are the items while the reviewers are the users

,artist,album,score,year,reviewer,genre,label,review_date,summary,review,best_new
0,Green-House,A Host for All Kinds of Life,7.6,2023,Hattie Lindert,Electronic / Experimental,Leaving,"October 23, 2023",The Los Angeles ambient musician continues to ...,For proof that we all must ultimately coexist ...,Not Available
1,Tkay Maidza,Sweet Justice,7.6,2023,Dylan Green,Pop/R&B,4AD,"November 3, 2023",The Australian musician chooses herself over t...,Tkay Maidza’s three-partLast Year Was WeirdEP ...,Not Available
2,A Giant Dog,Bite,6.4,2023,Linnie Greene,Rock,Merge,"August 28, 2023","On its first album in six years, the Austin gr...","A Giant Dog’sBite, the Austin, Texas, group’s ...",Not Available
3,Margaret Glaspy,Echo the Diamond,7.7,2023,Marc Hogan,Rock,ATO,"August 23, 2023","On her third album, the Brooklyn musician scra...",Margaret Glaspyhad only a couple of EPs to her...,Not Available
4,Maria BC,Spike Field,7.8,2023,Hannah Jocelyn,Rock / Experimental,Sacred Bones,"October 26, 2023","On their spectral new album, the Oakland music...","Since the 1980s, teams of engineers, anthropol...",Not Available
...,...,...,...,...,...,...,...,...,...,...,...
25703,Waco Brothers,Electric Waco Chair,7.2,Not Available,Not Available,Rock,Bloodshot,"October 17, 2000",The Waco Brothers should be awful. There shoul...,The Waco Brothers should be awful. There shoul...,Not Available
25704,Mansun,Little Kix,6.8,2000,Craig Griffith,Rock,Parlophone / EMI,"August 14, 2000",Top Ten Things I Thought I'd Never See:\n\n\n\...,Top Ten Things I Thought I'd Never See: 10. A ...,Not Available
25705,John Wesley Harding,Trad Arr Jones,7.3,Not Available,Not Available,Folk/Country,Zero Hour,"February 9, 1999","Needless to say, the headlines are more than a...","Needless to say, the headlines are more than a...",Not Available
25706,Cannibal Ox,The Cold Vein,8.3,2001,Christopher Dare,Rap,Definitive Jux,"May 15, 2001",I rented the filmRavenouslast weekend. I'm not...,I rented the filmRavenouslast weekend. I'm not...,Not Available
25707,Doves,Lost Souls,6.8,2000,Not Available,Rock,Astralwerks,"January 31, 2001","You know, we music journalists have to contend...","You know, we music journalists have to contend...",Not Available

# 1. Definición del problema de recomendación

Antes de programar, definid con claridad **qué problema vais a resolver**.

## Preguntas que debéis responder

1. ¿Qué es un ítem en vuestro problema?
2. ¿Existe usuario explícito o vais a trabajar solo con similitud entre ítems?
3. ¿Qué significa “recomendar bien” en vuestro caso?
4. ¿Queréis recomendar:
   - ítems parecidos a uno dado,
   - top-N para un usuario,
   - retrieval semántico a partir de una consulta,
   - o una combinación?
5. ¿Qué limitaciones tiene vuestro dataset para ese objetivo?

## Entregable de esta sección

Redactad una breve explicación del escenario de recomendación que vais a modelar.

1. Un ítem en nuestro problema es un álbum sacado por un artista/banda.
2. El usuario podrían ser los reviewers o podríamos eliminarlos y trabajar solo con similitudes, ya que muchos reviewers se repiten.
3. Dar una recomendación de canción acorde con el gusto de la persona.
4. Queremos dar albumnes parecidos a otros que el usuario guste.
5. ...

# 2. Análisis exploratorio y comprensión del dato

Realizad un EDA breve, orientado al problema.

No queremos un EDA enciclopédico, sino uno útil para decidir cómo construir el recomendador.

## Posibles aspectos sugeridos

- número de ítems,
- columnas disponibles,
- porcentaje de nulos,
- longitud de textos,
- frecuencia de categorías,
- distribución de ratings o interacciones (si existen),
- duplicados,
- problemas de calidad,
- idiomas mezclados,
- campos ruidosos,
- atributos muy informativos frente a atributos irrelevantes.

## Objetivo de esta sección

Que el EDA os ayude a responder:
- qué información merece la pena usar,
- qué hay que limpiar,
- y qué baseline tiene sentido construir.

In [2]:
# Espacio de trabajo: EDA y limpieza inicial
music = music.drop(columns=['reviewer', 'label', 'review_date', 'best_new'])
display(music.head(10))

,artist,album,score,year,genre,summary,review
0,Green-House,A Host for All Kinds of Life,7.6,2023,Electronic / Experimental,The Los Angeles ambient musician continues to ...,For proof that we all must ultimately coexist ...
1,Tkay Maidza,Sweet Justice,7.6,2023,Pop/R&B,The Australian musician chooses herself over t...,Tkay Maidza’s three-partLast Year Was WeirdEP ...
2,A Giant Dog,Bite,6.4,2023,Rock,"On its first album in six years, the Austin gr...","A Giant Dog’sBite, the Austin, Texas, group’s ..."
3,Margaret Glaspy,Echo the Diamond,7.7,2023,Rock,"On her third album, the Brooklyn musician scra...",Margaret Glaspyhad only a couple of EPs to her...
4,Maria BC,Spike Field,7.8,2023,Rock / Experimental,"On their spectral new album, the Oakland music...","Since the 1980s, teams of engineers, anthropol..."
5,Rhiannon Giddens,You’re the One,6.8,2023,Folk/Country,"On her first album of all original songs, the ...","As much archivist as poet,Rhiannon Giddenshas ..."
6,Eli Escobar,The Beach Album,7.8,2023,Electronic,The New York nightlife veteran’s new album chr...,When was the last time New York dance music wa...
7,Tomu DJ,Crazy Trip EP,7.2,Not Available,Experimental,The Oakland producer finds a middle ground bet...,"In 1992, Warp’sArtificial Intelligencecompilat..."
8,Mariah the Scientist,To Be Eaten Alive,6.3,2023,Pop/R&B,"Though often plodding and generic, the R&B sin...",Here’s atweetthat recently made me laugh: “You...
9,Kurt Vile,Back to Moon Beach EP,7.5,2023,Rock,"On an album-length EP, Kurt Vile finds darker ...",Kurt Vile’s time is slippery. Mondaysmeltunnot...

In [3]:
print(f"Rows, columns: {music.shape}")
print(f"Missing values: {music.isna().sum().sum()}")

# display(music[music.isna().any(axis=1)])

music = music.dropna()
display(music)

mean_sum = 0
for row in music['summary']:
    mean_sum += len(row)

mean_r = 0
for row in music['review']:
    mean_r += len(row)

print(f"Mean text length for summary column: {mean_sum / 25708}")
print(f"Mean text length for review column: {mean_r / 25708}")

genre_counts = music['genre'].value_counts(dropna=False)
frecuencia_abs = genre_counts[genre_counts > 800]

print(f"Genre frequency: {frecuencia_abs}")

music = music.drop_duplicates()
new_size = music.shape
print(f"Rows, columns afet duplicates and nans: {music.shape}")

Rows, columns: (25708, 7)
Missing values: 608

,artist,album,score,year,genre,summary,review
0,Green-House,A Host for All Kinds of Life,7.6,2023,Electronic / Experimental,The Los Angeles ambient musician continues to ...,For proof that we all must ultimately coexist ...
1,Tkay Maidza,Sweet Justice,7.6,2023,Pop/R&B,The Australian musician chooses herself over t...,Tkay Maidza’s three-partLast Year Was WeirdEP ...
2,A Giant Dog,Bite,6.4,2023,Rock,"On its first album in six years, the Austin gr...","A Giant Dog’sBite, the Austin, Texas, group’s ..."
3,Margaret Glaspy,Echo the Diamond,7.7,2023,Rock,"On her third album, the Brooklyn musician scra...",Margaret Glaspyhad only a couple of EPs to her...
4,Maria BC,Spike Field,7.8,2023,Rock / Experimental,"On their spectral new album, the Oakland music...","Since the 1980s, teams of engineers, anthropol..."
...,...,...,...,...,...,...,...
25703,Waco Brothers,Electric Waco Chair,7.2,Not Available,Rock,The Waco Brothers should be awful. There shoul...,The Waco Brothers should be awful. There shoul...
25704,Mansun,Little Kix,6.8,2000,Rock,Top Ten Things I Thought I'd Never See:\n\n\n\...,Top Ten Things I Thought I'd Never See: 10. A ...
25705,John Wesley Harding,Trad Arr Jones,7.3,Not Available,Folk/Country,"Needless to say, the headlines are more than a...","Needless to say, the headlines are more than a..."
25706,Cannibal Ox,The Cold Vein,8.3,2001,Rap,I rented the filmRavenouslast weekend. I'm not...,I rented the filmRavenouslast weekend. I'm not...
25707,Doves,Lost Souls,6.8,2000,Rock,"You know, we music journalists have to contend...","You know, we music journalists have to contend..."

Mean text length for summary column: 167.5177765676054
Mean text length for review column: 4080.211918468959
Genre frequency: genre
Rock                 8635
Electronic           2970
Rap                  2366
Not Available        2347
Pop/R&B              1695
Experimental         1236
Electronic / Rock    1040
Folk/Country          871
Name: count, dtype: int64
Rows, columns afet duplicates and nans: (25078, 7)

In [7]:
# elimina saltos de línea de cada resumen
music['summary'] = music['summary'].str.replace("\n", " ", regex=False)
music['review'] = music['review'].str.replace("\n", " ", regex=False)
print(music)

                    artist                         album score           year  \
0              Green-House  A Host for All Kinds of Life   7.6           2023
1              Tkay Maidza                 Sweet Justice   7.6           2023
2              A Giant Dog                          Bite   6.4           2023
3          Margaret Glaspy              Echo the Diamond   7.7           2023
4                 Maria BC                   Spike Field   7.8           2023
...                    ...                           ...   ...            ...
25703        Waco Brothers           Electric Waco Chair   7.2  Not Available
25704               Mansun                    Little Kix   6.8           2000
25705  John Wesley Harding                Trad Arr Jones   7.3  Not Available
25706          Cannibal Ox                 The Cold Vein   8.3           2001
25707                Doves                    Lost Souls   6.8           2000

                           genre  \
0      Electronic / Experimental
1                        Pop/R&B
2                           Rock
3                           Rock
4            Rock / Experimental
...                          ...
25703                       Rock
25704                       Rock
25705               Folk/Country
25706                        Rap
25707                       Rock

                                                 summary  \
0      The Los Angeles ambient musician continues to ...
1      The Australian musician chooses herself over t...
2      On its first album in six years, the Austin gr...
3      On her third album, the Brooklyn musician scra...
4      On their spectral new album, the Oakland music...
...                                                  ...
25703  The Waco Brothers should be awful. There shoul...
25704  Top Ten Things I Thought I'd Never See: \n\n\ ...
25705  Needless to say, the headlines are more than a...
25706  I rented the filmRavenouslast weekend. I'm not...
25707  You know, we music journalists have to contend...

                                                  review
0      For proof that we all must ultimately coexist ...
1      Tkay Maidza’s three-partLast Year Was WeirdEP ...
2      A Giant Dog’sBite, the Austin, Texas, group’s ...
3      Margaret Glaspyhad only a couple of EPs to her...
4      Since the 1980s, teams of engineers, anthropol...
...                                                  ...
25703  The Waco Brothers should be awful. There shoul...
25704  Top Ten Things I Thought I'd Never See: 10. A ...
25705  Needless to say, the headlines are more than a...
25706  I rented the filmRavenouslast weekend. I'm not...
25707  You know, we music journalists have to contend...

[25078 rows x 7 columns]

# 3. Ingeniería de representación del ítem

Esta es una de las partes más importantes de la práctica.

Los embeddings no “hacen magia” si la entrada está mal planteada.

## Tarea

Debéis diseñar **una o varias estrategias de representación textual** del ítem.

### Ejemplos de preguntas útiles

- ¿Uso solo la descripción?
- ¿Añado título al principio?
- ¿Repito o pondero ciertos campos?
- ¿Convierto listas de tags en lenguaje natural?
- ¿Mantengo campos estructurados como texto tipo `género: acción | drama`?
- ¿Incluyo atributos numéricos transformados a texto?
- ¿Merece la pena concatenar todo o genera ruido?
- ¿Es mejor una representación corta y precisa o una más rica y larga?

## Requisito obligatorio

Debéis probar **al menos una estrategia razonada** de construcción del string de entrada.

## Recomendación fuerte

Probad **dos o más variantes** y comentad:
- cuál parece funcionar mejor,
- cuál es más interpretable,
- y cuál introduce más ruido.

## Ejemplos de variantes posibles

- Variante A: título + descripción.
- Variante B: título + descripción + categorías.
- Variante C: título + descripción + categorías + tags + autor.
- Variante D: formato más “natural” en frases.
- Variante E: formato más “estructurado” tipo campos etiquetados.

In [ ]:
# TODO:
# construir una o varias funciones que conviertan cada ítem en un string
# justificar las decisiones tomadas

# 4. Baselines tradicionales

Debéis implementar **uno o varios modelos tradicionales** con los que comparar.

## Posibles opciones

### Opción A — Baseline muy sencillo
Un sistema simple por:
- popularidad,
- rating medio,
- weighted rating,
- frecuencia de consumo,
- score heurístico.

### Opción B — Baseline content-based clásico
Un sistema basado en:
- TF-IDF + cosine similarity,
- CountVectorizer + cosine similarity,
- metadata soup clásica.

### Opción C — Baseline colaborativo
Si vuestro dataset tiene interacciones usuario–ítem:
- user-based CF,
- item-based CF,
- kNN,
- SVD / matrix factorization.

## Qué esperamos

No os limitéis a “ejecutar una librería”.

Explicad:
- qué hace el baseline,
- por qué es razonable,
- y por qué es una referencia justa frente al modelo moderno.

In [ ]:
# Espacio de trabajo: baseline 1

In [ ]:
# Espacio de trabajo: baseline 2 (opcional pero recomendado)

# 5. Recomendador basado en embeddings modernos

Implementad aquí vuestro modelo principal.

## Posibles estrategias

### Estrategia 1 — Ítem a ítem
- obtenéis embeddings de todos los ítems,
- calculáis similitud,
- y recomendáis los más cercanos.

### Estrategia 2 — Perfil de usuario
- agregáis embeddings de ítems consumidos / valorados positivamente,
- construís un embedding de usuario,
- y recomendáis por cercanía.

### Estrategia 3 — Query semántica
- representáis una necesidad del usuario como texto,
- la convertís a embedding,
- y recuperáis ítems cercanos.

### Estrategia 4 — Híbrido
- usáis embeddings para recuperar candidatos,
- y luego reordenáis con otra señal:
  popularidad, rating, collaborative score, filtros de negocio, etc.

## Qué debéis justificar

- modelo o servicio usado para obtener embeddings,
- coste / velocidad / facilidad de uso,
- dimensión de embeddings,
- función de similitud,
- si normalizáis o no,
- cómo hacéis retrieval,
- y por qué vuestra decisión tiene sentido para el dataset elegido.

In [ ]:
# Espacio de trabajo: generación de embeddings

In [ ]:
# Espacio de trabajo: recomendador con embeddings

# 6. Diseño de la evaluación

Esta sección es clave.

Una práctica de recomendación no se defiende solo con ejemplos bonitos. Necesitáis un protocolo experimental razonable.

## Preguntas guía

### 1. ¿Qué vais a evaluar exactamente?
- predicción de rating,
- ranking top-N,
- recuperación de ítems relevantes,
- similitud semántica útil,
- utilidad para usuario,
- o una combinación.

### 2. ¿Cómo vais a construir train/test?
Algunas posibilidades:
- split aleatorio,
- leave-one-out por usuario,
- temporal split,
- ocultar interacciones,
- evaluación de recuperación sobre ítems conocidos,
- o escenarios simulados.

### 3. ¿Qué métricas usaréis?
Dependiendo del caso, podrían tener sentido:
- Precision@k,
- Recall@k,
- MAP@k,
- MRR,
- NDCG@k,
- Hit Rate@k,
- RMSE / MAE,
- cobertura,
- diversidad,
- novedad,
- serendipia,
- tiempo de cómputo.

## Requisito obligatorio

Debéis **investigar y justificar** por qué vuestras métricas son adecuadas para vuestro problema.

No aceptaremos una métrica elegida “porque sí”.

## Pregunta central

Al terminar esta sección deberíais poder responder con honestidad:

> ¿Hay evidencia de mejora real frente al baseline?

In [ ]:
# Espacio de trabajo: preparación del protocolo de evaluación

In [ ]:
# Espacio de trabajo: cálculo de métricas

# 7. Comparación cualitativa

Además de los números, mostrad ejemplos concretos.

## Qué incluir

Para varios casos de prueba, enseñad:
- recomendaciones del baseline,
- recomendaciones del modelo con embeddings,
- y comentario crítico sobre las diferencias.

## Preguntas útiles

- ¿El modelo con embeddings captura mejor matices semánticos?
- ¿Recomienda cosas demasiado obvias?
- ¿Introduce variedad útil?
- ¿Se deja engañar por ruido textual?
- ¿Empeora cuando faltan metadatos?
- ¿Se parece demasiado a un buscador semántico en vez de a un recomendador?

In [ ]:
# Espacio de trabajo: comparación cualitativa de recomendaciones

# 8. Retos, limitaciones y discusión

En esta práctica no buscamos solo un resultado “bonito”.

Queremos también pensamiento crítico.

## Debéis discutir, al menos, algunos de estos puntos

- sensibilidad a cómo construís el texto,
- dependencia de la calidad del dataset,
- ruido en categorías / tags / descripciones,
- coste de generar embeddings,
- escalabilidad,
- problema de cold start,
- necesidad o no de interacción usuario–ítem,
- interpretabilidad,
- sesgo hacia popularidad,
- sesgo hacia similitud superficial,
- dificultad para evaluar offline,
- y posibles riesgos de sobreinterpretar pequeñas mejoras.

## Pregunta importante

¿En qué escenarios pensáis que el enfoque con embeddings modernos **sí** tiene ventaja clara?

¿Y en cuáles un método más clásico puede seguir siendo:
- suficiente,
- más barato,
- más interpretable,
- o incluso mejor?

In [ ]:
# TODO: discusión crítica final

# 9. Conclusiones

Cerrad el trabajo con una conclusión breve pero sólida.

## Debe responder, como mínimo, a estas preguntas

1. ¿Qué habéis construido?
2. ¿Con qué lo habéis comparado?
3. ¿Cuál ha funcionado mejor y según qué métricas?
4. ¿Qué habéis aprendido sobre diseñar recomendadores con embeddings?
5. ¿Qué mejoraríais si tuvierais más tiempo?

In [ ]:
# TODO: conclusiones finales

# Entregables

## Entrega obligatoria

Debéis entregar:

1. **Este notebook** completo y ejecutable.
2. Los ficheros auxiliares necesarios para reproducir el experimento.
3. Un **README breve** con:
   - dataset usado,
   - instrucciones de ejecución,
   - dependencias,
   - y resumen de resultados.
4. Una breve sección final o anexo con:
   - retos,
   - limitaciones,
   - y líneas futuras.

## Reproducibilidad

El notebook debe poder entenderse y ejecutarse con claridad.

No hace falta que todo sea perfecto, pero sí que:
- el flujo tenga sentido,
- las decisiones estén justificadas,
- y las conclusiones estén apoyadas por resultados.

# Criterios de evaluación sugeridos

## 1. Planteamiento del problema
- claridad del objetivo,
- adecuación del dataset,
- coherencia del escenario de recomendación.

## 2. Calidad del pipeline
- limpieza,
- preparación,
- construcción de la representación,
- reproducibilidad.

## 3. Baselines
- que existan,
- que sean razonables,
- y que la comparación sea justa.

## 4. Modelo con embeddings
- calidad de la idea,
- corrección de la implementación,
- justificación técnica.

## 5. Evaluación
- calidad del protocolo,
- elección de métricas,
- rigor del análisis.

## 6. Discusión crítica
- interpretación honesta,
- identificación de limitaciones,
- propuestas de mejora.

## 7. Comunicación
- notebook claro,
- figuras o tablas útiles,
- redacción limpia,
- conclusiones comprensibles.

# Pistas y consejos

## Consejo 1
No intentéis construir el recomendador “más complejo posible” desde el minuto uno.

Primero haced que funcione un baseline simple y un pipeline básico.

## Consejo 2
En recomendación, muchas veces una gran parte del rendimiento depende de:
- cómo definís el problema,
- cómo preparáis los datos,
- y cómo evaluáis.

## Consejo 3
Las mejoras pequeñas pueden ser reales… o ruido experimental.

Sed prudentes al interpretar resultados.

## Consejo 4
No confundáis:
- similitud semántica,
- recomendación útil,
- ranking,
- y predicción de preferencia.

Están relacionados, pero no son exactamente lo mismo.

## Consejo 5
Una muy buena práctica es incluir una pequeña tabla resumen final con:
- modelo,
- representación usada,
- métricas,
- ventajas,
- limitaciones.

# Extensiones opcionales

Si queréis subir nivel, podéis intentar alguna de estas extensiones:

- usar varias estrategias de construcción del string y compararlas,
- hacer un pequeño estudio de ablación,
- combinar embeddings con popularidad o collaborative filtering,
- añadir reranking,
- estudiar diversidad y cobertura además de precisión,
- crear una demo sencilla,
- analizar fallos,
- o proponer una versión para producción.

# Cierre

## Mensaje final

El objetivo de esta práctica no es demostrar que “lo moderno siempre gana”.

El objetivo es aprender a responder con datos, método y criterio a una pregunta muy real en sistemas de recomendación:

> **¿Cuándo merece la pena pasar de un enfoque clásico a uno basado en embeddings modernos?**

Buena suerte, y defended vuestras decisiones con claridad.